# Generated by Django 5.2 on 2025-04-18 09:15

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(editable=False, unique=True)),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(editable=False, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(editable=False, unique=True)),
                (
                    "summary",
                    models.TextField(
                        help_text="A brief excerpt or summary of the content"
                    ),
                ),
                (
                    "content",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, help_text="Main content body", null=True
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("SERMON", "Sermon"),
                            ("BOOK", "Book"),
                            ("WRITE_UP", "Write-Up"),
                        ],
                        default="WRITE_UP",
                        max_length=20,
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="content/featured/"
                    ),
                ),
                (
                    "external_links",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON field for external links",
                    ),
                ),
                ("spotify_link", models.URLField(blank=True)),
                ("youtube_link", models.URLField(blank=True)),
                ("download_link", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("publication_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("downloads_count", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="core.category",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="contents", to="core.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-publication_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-publication_date", "-created_at"],
                        name="core_conten_publica_57b57b_idx",
                    ),
                    models.Index(
                        fields=["status"], name="core_conten_status_906741_idx"
                    ),
                    models.Index(
                        fields=["content_type"], name="core_conten_content_c62a22_idx"
                    ),
                ],
            },
        ),
    ]
