# Generated by Django 5.2 on 2025-05-01 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_backgroundimage_remove_quote_background_image_1_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("slug", models.SlugField(editable=False, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Category image for display in cards",
                        null=True,
                        upload_to="quote_categories/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quote Category",
                "verbose_name_plural": "Quote Categories",
                "ordering": ["id"],
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.RemoveField(
            model_name="quote",
            name="content",
        ),
        migrations.AddField(
            model_name="quote",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_quotes",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quote",
            name="featured",
            field=models.BooleanField(
                default=False, help_text="Featured quotes will be displayed prominently"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                default="DRAFT",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="quote_tags", to="core.tag"
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="quote",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotes",
                to="core.quotecategory",
            ),
        ),
    ]
