# Generated by Django 5.2 on 2025-05-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_quotecategory_alter_category_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="backgroundimage",
            name="image_url",
        ),
        migrations.AddField(
            model_name="backgroundimage",
            name="image",
            field=models.ImageField(
                default="BG1.png",
                help_text="Background image for quotes (1080x1080 px recommended)",
                upload_to="backgrounds/",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="content",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("SERMON", "Sermon"),
                    ("BOOK", "Book"),
                    ("WRITE_UP", "Write-Up"),
                ],
                default="WRITE_UP",
                max_length=20,
            ),
        ),
    ]
