# Generated by Django 5.2 on 2025-05-03 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_backgroundimage_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="default_font_style",
            field=models.CharField(
                choices=[
                    ("ARIAL", "Arial"),
                    ("TIMES", "Times New Roman"),
                    ("ROBOTO", "Roboto"),
                    ("MONTSERRAT", "Montserrat"),
                    ("OPENSANS", "Open Sans"),
                    ("LATO", "Lato"),
                    ("POPPINS", "Poppins"),
                ],
                default="ARIAL",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("author_name", models.CharField(max_length=100)),
                (
                    "synopsis",
                    models.TextField(help_text="Brief description of the book"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        help_text="Book cover image", upload_to="books/covers/"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        help_text="PDF file for download", upload_to="books/files/"
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("publisher", models.CharField(blank=True, max_length=100)),
                (
                    "isbn",
                    models.CharField(
                        blank=True, help_text="ISBN number if available", max_length=20
                    ),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of pages", null=True
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("downloads_count", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="core.category",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="core.subcategory",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="books", to="core.tag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["-created_at"],
            },
        ),
    ]
