# Generated by Django 5.2 on 2025-05-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_quote_default_font_style_book"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        default="Apostle Niyi Digital Library", max_length=100
                    ),
                ),
                (
                    "site_description",
                    models.TextField(
                        blank=True,
                        default="Digital Library for Apostle Niyi Makinde's content",
                    ),
                ),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("items_per_page", models.PositiveIntegerField(default=12)),
                ("maintenance_mode", models.BooleanField(default=False)),
                (
                    "maintenance_message",
                    models.TextField(
                        blank=True,
                        default="We're currently performing maintenance. Please check back soon.",
                    ),
                ),
                ("last_db_backup", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
