# Generated by Django 5.2 on 2025-05-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_sitesettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="default_font_style",
            field=models.CharField(
                choices=[
                    ("ARIAL", "Arial"),
                    ("TIMES", "Times New Roman"),
                    ("DAILYQUOTES", "Daily Quotes"),
                    ("LATO-BOLD", "Lato Italic"),
                    ("LATO-ITALIC", "Lato Italic"),
                    ("LATO-REGULAR", "Lato Regular"),
                    ("POPPINS-ITALIC", "Poppins Italic"),
                    ("POPPINS-REGULAR", "Poppins Regular"),
                    ("POPPINS-THIN", "Poppins Thin"),
                    ("QUOTE", "Quote"),
                ],
                default="ARIAL",
                max_length=20,
            ),
        ),
    ]
